name: 'Build RPM'
description: 'Automate the process of building RPM packages and source RPMs from spec files'
inputs:
  mock-configuration:
    description: 'Mock configuration to use'
    required: false
    default: epel-8-x86_64
  repo-host:
    description: 'Repository host URL for custom packages'
    required: false
    default: http://localhost
  srpm_output_folder:
    description: 'Output folder for generated source RPM (SRPM) files'
    required: true
    default: /srpm
  rpm_output_folder:
    description: 'Output folder for generated RPM files'
    required: true
  spec_file:
    description: 'List of spec files to build RPMs'
    required: true
    default: '*.spec'
outputs:
  result:
    description: 'Build RPMs'
runs:
  using: 'composite'
  steps:
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'
    - name: Build using docker
      run: >
        docker run --privileged=true --rm -v $(pwd):/mnt -v ${{ inputs.rpm_output_folder }}:/rpm -w /mnt --add-host server:127.0.0.1 eljhoset/hello-build
        -r ${{ inputs.mock-configuration }} --repo-host '${{ inputs.repo-host }}' -s ${{ inputs.srpm_output_folder }} -o /rpm '${{ inputs.spec_file }}'
      shell: bash
    - name: Set output
      run: echo "result=$(ls ${{ inputs.rpm_output_folder }})" >> $GITHUB_OUTPUT
      shell: bash
    - name: Upload to Artifact Registry
        run: |
          gcloud config set artifacts/repository gcp-repo
          gcloud config set artifacts/location us-east1          
          gcloud artifacts yum upload --source=$(ls $GITHUB_WORKSPACE/${{ inputs.rpm_output_folder }}/*.rpm | grep -vE '(src|debug)')
